In [676]:
import pandas as pd

In [677]:
pd.set_option('min_rows', 50)

In [678]:
file = "../../data/2024_O1_I1_AUT.CSV"
column_names = ["chapa", "comprimento chapa (mm)", "largura chapa (mm)", "material chapa", 
                "espessura chapa (mm)", "quantidade chapa", "area chapa (mm2)", "peso chapa (kg)",
                "eficiencia chapa (%)", "quantidade golpes", ""]
columns_to_int = ["comprimento chapa (mm)", "largura chapa (mm)",
                  "quantidade chapa", "quantidade golpes"
                ]

In [679]:
autonest_df = pd.read_csv(file, encoding='latin')

In [680]:
print(autonest_df)

                                                Order:  \
0                                                Date:
1                                                Time:
2                                             Machine:
3                                               Notes:
4                                                  NaN
5                              Total number of sheets:
6                            Total Number of SubNests:
7                                    Order Efficiency:
8                                                  NaN
9                                 Total ordered parts:
10                                 Total Placed Parts:
11                                                 NaN
12                                                 NaN
13                                  SubNests in order:
14   ----------------------------------------------...
15                                            Plate#
16   ----------------------------------------------...
17                                                  1
18                                                  2
19                                                  3
20                                                  4
21                                                  5
22                                                  6
23                                                  7
24                                                  8
..                                                 ...
503                                         -1
504                                         -1
505                                         -1
506                                         -1
507                                         -1
508                                         -1
509                                         -1
510                                         -1
511                                         -1
512                                         -1
513                                         -1
514                                         -1
515                                         -1
516                                         -1
517                                         -1
518                                         -1
519                                         -1
520                                         -1
521                                         -1
522                                         -1
523  ----------------------------------------------...
524  Nozzle diameter \t         ,"Beam diameter(Ker...
525  ----------------------------------------------...
526                       @LAS'PIERCE'REDUSED_FEEDRATE
527  ----------------------------------------------...

                      2024_O1_I1.dsp                 Unnamed: 2  \
0                            Tuesday               September 12
1                           22:08:23                        NaN
2                             DU_TP9                        NaN
3                                NaN                        NaN
4                                NaN                        NaN
5                                 39                        NaN
6                                 38                        NaN
7                              80.29                        NaN
8                                NaN                        NaN
9                                250                        NaN
10                               250                        NaN
11                               NaN                        NaN
12                               NaN                        NaN
13                               NaN                        NaN
14                               NaN                        NaN
15                       Size X                     Size Y
16                               NaN                        NaN
17                             2200                       1200
18                             2200                       1200
19                             2200                       1200
20                             2200                       1200
21                             2200                       1200
22                             2200                       1200
23                             2200                       1200
24                             2200                       1200
..                               ...                        ...
503                      -1
504                      -1
505                      -1
506                      -1
507                      -1
508                      -1
509                      -1
510                      -1
511                      -1
512                      -1
513                      -1
514                      -1
515                      -1
516                      -1
517                      -1
518                      -1
519                      -1
520                      -1
521                      -1
522                      -1
523                              NaN                        NaN
524                              NaN                        NaN
525                              NaN                        NaN
526  @LAS'CUT'BEAM_DIAMETER'HIGH_CUT  @LAS'CUT'OUTPUT'HIGH_CUT
527                              NaN                        NaN

               Unnamed: 3  Unnamed: 4 Unnamed: 5  Unnamed: 6 Unnamed: 7  \
0                2023             NaN        NaN         NaN        NaN
1                     NaN         NaN        NaN         NaN        NaN
2                     NaN         NaN        NaN         NaN        NaN
3                     NaN         NaN        NaN         NaN        NaN
4                     NaN         NaN        NaN         NaN        NaN
5                     NaN         NaN        NaN         NaN        NaN
6                     NaN         NaN        NaN         NaN        NaN
7                     NaN         NaN        NaN         NaN        NaN
8                     NaN         NaN        NaN         NaN        NaN
9                     NaN         NaN        NaN         NaN        NaN
10                    NaN         NaN        NaN         NaN        NaN
11                    NaN         NaN        NaN         NaN        NaN
12                    NaN         NaN        NaN         NaN        NaN
13                    NaN         NaN        NaN         NaN        NaN
14                    NaN         NaN        NaN         NaN        NaN
15           Material      Thickness    Qty       Area        Weight
16                    NaN         NaN        NaN         NaN        NaN
17   ACO NBR 7008 ZC          0.95            1       2.64     19.688
18   ACO NBR 7008 ZC          0.95            1       2.64     19.688
19   ACO NBR 7008 ZC          0.95            1       2.64     19.688
20   ACO NBR 7008 ZC          1.95            1       2.64     40.412
21   ACO NBR 7008 ZC          1.95            1       2.64     40.412
22   ACO NBR 7008 ZC          1.95            1       2.64     40.412
23   ACO NBR 7008 ZC          1.95            1       2.64     40.412
24   ACO NBR 7008 ZC          1.95            1       2.64     40.412
..                    ...         ...        ...         ...        ...
503                   -1          NaN        NaN         NaN        NaN
504                   -1          NaN        NaN         NaN        NaN
505                   -1          NaN        NaN         NaN        NaN
506                   -1          NaN        NaN         NaN        NaN
507                   -1          NaN        NaN         NaN        NaN
508                   -1          NaN        NaN         NaN        NaN
509                   -1          NaN        NaN         NaN        NaN
510                   -1          NaN        NaN         NaN        NaN
511                   -1          NaN        NaN         NaN        NaN
512                   -1          NaN        NaN         NaN        NaN
513                   -1          NaN        NaN         NaN        NaN
514                   -1          NaN        NaN         NaN        NaN
515                   -1          NaN        NaN         NaN        NaN
516                   -1          NaN        NaN         NaN        NaN
517                   -1          NaN        NaN         NaN        NaN
518                   -1          NaN        NaN         NaN        NaN
519                   -1          NaN        NaN         NaN        NaN
520                   -1          NaN        NaN         NaN        NaN
521                   -1          NaN        NaN         NaN        NaN
522                   -1          NaN        NaN         NaN        NaN
523                   NaN         NaN        NaN         NaN        NaN
524                   NaN         NaN        NaN         NaN        NaN
525                   NaN         NaN        NaN         NaN        NaN
526                   NaN         NaN        NaN         NaN        NaN
527                   NaN         NaN        NaN         NaN        NaN

        Unnamed: 8 Unnamed: 9  Unnamed: 10
0              NaN        NaN          NaN
1              NaN        NaN          NaN
2              NaN        NaN          NaN
3              NaN        NaN          NaN
4              NaN        NaN          NaN
5              NaN        NaN          NaN
6              NaN        NaN          NaN
7              NaN        NaN          NaN
8              NaN        NaN          NaN
9              NaN        NaN          NaN
10             NaN        NaN          NaN
11             NaN        NaN          NaN
12             NaN        NaN          NaN
13             NaN        NaN          NaN
14             NaN        NaN          NaN
15   Efficiency       Punches          NaN
16             NaN        NaN          NaN
17       56.51            448          NaN
18       50.84            571          NaN
19       65.82            705          NaN
20       85.62            838          NaN
21       90.39            824          NaN
22       86.26           1094          NaN
23       89.46           1000          NaN
24       88.27           1214          NaN
..             ...        ...          ...
503            NaN        NaN          NaN
504            NaN        NaN          NaN
505            NaN        NaN          NaN
506            NaN        NaN          NaN
507            NaN        NaN          NaN
508            NaN        NaN          NaN
509            NaN        NaN          NaN
510            NaN        NaN          NaN
511            NaN        NaN          NaN
512            NaN        NaN          NaN
513            NaN        NaN          NaN
514            NaN        NaN          NaN
515            NaN        NaN          NaN
516            NaN        NaN          NaN
517            NaN        NaN          NaN
518            NaN        NaN          NaN
519            NaN        NaN          NaN
520            NaN        NaN          NaN
521            NaN        NaN          NaN
522            NaN        NaN          NaN
523            NaN        NaN          NaN
524            NaN        NaN          NaN
525            NaN        NaN          NaN
526            NaN        NaN          NaN
527            NaN        NaN          NaN

[528 rows x 11 columns]

In [681]:
first_column = autonest_df.iloc[:, 0]

In [682]:
print(first_column)

0                                                  Date:
1                                                  Time:
2                                               Machine:
3                                                 Notes:
4                                                    NaN
5                                Total number of sheets:
6                              Total Number of SubNests:
7                                      Order Efficiency:
8                                                    NaN
9                                   Total ordered parts:
10                                   Total Placed Parts:
11                                                   NaN
12                                                   NaN
13                                    SubNests in order:
14     ----------------------------------------------...
15                                              Plate#
16     ----------------------------------------------...
17                                                    1
18                                                    2
19                                                    3
20                                                    4
21                                                    5
22                                                    6
23                                                    7
24                                                    8
                             ...
503                                           -1
504                                           -1
505                                           -1
506                                           -1
507                                           -1
508                                           -1
509                                           -1
510                                           -1
511                                           -1
512                                           -1
513                                           -1
514                                           -1
515                                           -1
516                                           -1
517                                           -1
518                                           -1
519                                           -1
520                                           -1
521                                           -1
522                                           -1
523    ----------------------------------------------...
524    Nozzle diameter \t         ,"Beam diameter(Ker...
525    ----------------------------------------------...
526                         @LAS'PIERCE'REDUSED_FEEDRATE
527    ----------------------------------------------...
Name: Order:, Length: 528, dtype: object

In [683]:
#first_column = first_column.astype(int, errors='ignore')

In [684]:
#print(first_column)

In [685]:
autonest_df.iloc[:, 0] = pd.to_numeric(first_column, errors='coerce')

In [686]:
autonest_df.iloc[:, 0].dropna()

17      1.0
18      2.0
19      3.0
20      4.0
21      5.0
22      6.0
23      7.0
24      8.0
25      9.0
26     10.0
27     11.0
28     12.0
29     13.0
30     14.0
31     15.0
32     16.0
33     17.0
34     18.0
35     19.0
36     20.0
37     21.0
38     22.0
39     23.0
40     24.0
41     25.0
       ...
498    -1.0
499    -1.0
500    -1.0
501    -1.0
502    -1.0
503    -1.0
504    -1.0
505    -1.0
506    -1.0
507    -1.0
508    -1.0
509    -1.0
510    -1.0
511    -1.0
512    -1.0
513    -1.0
514    -1.0
515    -1.0
516    -1.0
517    -1.0
518    -1.0
519    -1.0
520    -1.0
521    -1.0
522    -1.0
Name: Order:, Length: 192, dtype: object

In [687]:
index_rows = autonest_df.index[first_column == autonest_df.iloc[:, 0]].tolist()

In [688]:
autonest_df = autonest_df.filter(items=index_rows, axis=0)

In [689]:
autonest_df = autonest_df.loc[first_column > 0]

In [690]:
autonest_df.columns = column_names

In [691]:
autonest_df = autonest_df.drop("", axis=1)

In [692]:
print(autonest_df[columns_to_int])

   comprimento chapa (mm) largura chapa (mm) quantidade chapa  \
17                  2200               1200                1
18                  2200               1200                1
19                  2200               1200                1
20                  2200               1200                1
21                  2200               1200                1
22                  2200               1200                1
23                  2200               1200                1
24                  2200               1200                1
25                  2200               1200                1
26                  2200               1200                1
27                  2200               1200                1
28                  2200               1200                1
29                  2200               1200                1
30                  2200               1200                1
31                  2200               1200                1
32                  2200               1200                1
33                  2200               1200                1
34                  2200               1200                1
35                  2200               1200                1
36                  2200               1200                1
37                  1200                800                1
38                   650                300                1
39                  2200               1200                2
40                  2200               1200                1
41                  2200               1200                1
42                  2200               1200                1
43                  2200               1200                1
44                  2200               1200                1
45                  2200               1200                1
46                  2200               1200                1
47                  2200               1200                1
48                  2200               1200                1
49                  2200               1200                1
50                  2200               1200                1
51                  2200               1200                1
52                  2200               1200                1
53                  2200               1200                1
54                  2200               1200                1

   quantidade golpes
17               448
18               571
19               705
20               838
21               824
22              1094
23              1000
24              1214
25              1026
26              1198
27               876
28               757
29               562
30               640
31               564
32               543
33              1062
34              1061
35               660
36               359
37               304
38               304
39                36
40               183
41               318
42               359
43               358
44               461
45               469
46               477
47               430
48               332
49               420
50               285
51               339
52               203
53               327
54               445

In [693]:
autonest_df["comprimento chapa (mm)"] = pd.to_numeric(autonest_df["comprimento chapa (mm)"], errors='coerce')
print(autonest_df["comprimento chapa (mm)"])

17    2200
18    2200
19    2200
20    2200
21    2200
22    2200
23    2200
24    2200
25    2200
26    2200
27    2200
28    2200
29    2200
30    2200
31    2200
32    2200
33    2200
34    2200
35    2200
36    2200
37    1200
38     650
39    2200
40    2200
41    2200
42    2200
43    2200
44    2200
45    2200
46    2200
47    2200
48    2200
49    2200
50    2200
51    2200
52    2200
53    2200
54    2200
Name: comprimento chapa (mm), dtype: int64

In [694]:
autonest_df[columns_to_int] = pd.to_numeric(columns_to_int, errors='coerce')

In [695]:
print(autonest_df[columns_to_int])

    comprimento chapa (mm)  largura chapa (mm)  quantidade chapa  \
17                     NaN                 NaN               NaN
18                     NaN                 NaN               NaN
19                     NaN                 NaN               NaN
20                     NaN                 NaN               NaN
21                     NaN                 NaN               NaN
22                     NaN                 NaN               NaN
23                     NaN                 NaN               NaN
24                     NaN                 NaN               NaN
25                     NaN                 NaN               NaN
26                     NaN                 NaN               NaN
27                     NaN                 NaN               NaN
28                     NaN                 NaN               NaN
29                     NaN                 NaN               NaN
30                     NaN                 NaN               NaN
31                     NaN                 NaN               NaN
32                     NaN                 NaN               NaN
33                     NaN                 NaN               NaN
34                     NaN                 NaN               NaN
35                     NaN                 NaN               NaN
36                     NaN                 NaN               NaN
37                     NaN                 NaN               NaN
38                     NaN                 NaN               NaN
39                     NaN                 NaN               NaN
40                     NaN                 NaN               NaN
41                     NaN                 NaN               NaN
42                     NaN                 NaN               NaN
43                     NaN                 NaN               NaN
44                     NaN                 NaN               NaN
45                     NaN                 NaN               NaN
46                     NaN                 NaN               NaN
47                     NaN                 NaN               NaN
48                     NaN                 NaN               NaN
49                     NaN                 NaN               NaN
50                     NaN                 NaN               NaN
51                     NaN                 NaN               NaN
52                     NaN                 NaN               NaN
53                     NaN                 NaN               NaN
54                     NaN                 NaN               NaN

    quantidade golpes
17                NaN
18                NaN
19                NaN
20                NaN
21                NaN
22                NaN
23                NaN
24                NaN
25                NaN
26                NaN
27                NaN
28                NaN
29                NaN
30                NaN
31                NaN
32                NaN
33                NaN
34                NaN
35                NaN
36                NaN
37                NaN
38                NaN
39                NaN
40                NaN
41                NaN
42                NaN
43                NaN
44                NaN
45                NaN
46                NaN
47                NaN
48                NaN
49                NaN
50                NaN
51                NaN
52                NaN
53                NaN
54                NaN

In [696]:
autonest_df = autonest_df.groupby(["comprimento chapa (mm)", "largura chapa (mm)", "espessura chapa (mm)", "material chapa"]).sum()

In [697]:
display(autonest_df)

Empty DataFrame
Columns: [chapa, quantidade chapa, area chapa (mm2), peso chapa (kg), eficiencia chapa (%), quantidade golpes]
Index: []